### ISSUE TITLE
erros in visualization

### ISSUE THREAD

**Issue by Jiangchao3** [noaa-ocs-modeling/adcircpy#135]
Hi @jreniel and @zacharyburnettNOAA @krober10nd 

I am trying to use adcircpy to visualize some simulation results but some errors occur. (the mesh and input file is maken by OceanMesh2D)

for mesh

![image](https://user-images.githubusercontent.com/66854878/135618206-fa030243-66a7-45d9-8ec6-faab3530674d.png)

for fort.61.nc

![image](https://user-images.githubusercontent.com/66854878/135618323-d48a7b85-cb3f-4800-8607-918dcf7cb4f0.png)

for maxele, no errors occur, but I can not find a figure in the current folder, not sure the plot is successful or not.

![image](https://user-images.githubusercontent.com/66854878/135618406-0224050f-c5fb-48e7-9708-26d3215385f0.png)

Any suggestions to fix the error or other visualization tools recommended? Many thanks to you.

Jiangchao

**Comment by krober10nd** [comment]
I would just read in the data into python from the netcdf file and plot it using matplotlib. 

These plot utilities are just for sanity checking IMO.

**Comment by Jiangchao3** [comment]
Got it. Many thanks, I will have a try using python.
