### ISSUE TITLE
respecting version numbers

### ISSUE THREAD

**Issue by krober10nd** [noaa-ocs-modeling/adcircpy#138]
* I've just noticed that going from 1.0.40 to 1.0.41 many fields of the `mesh` class have become Pandas dataframes? This unfortunately breaks all of my existing codes and is a pretty major change. 
* Next time, if the API changes can we please increment a major version number?

**Comment by ghost** [comment]
sorry I did not see this issue until now. Yes, I apologize, I hadn't thought to test for major API changes. I will keep that in mind in future version updates, sorry!
