### ISSUE TITLE
pre-process best track file for running awisp

### ISSUE THREAD

**Issue by Jiangchao3** [noaa-ocs-modeling/adcircpy#169]
Hi @zacharyburnett @jreniel @krober10nd ,

I am trying to use NWS 20 mode to run adcirc. I met same error that Keith post in the adcirc mailing list. 

 ERROR: aswip:           83  isotachs were nonzero.
 ERROR: aswip:           88  isotachs were nonzero.
 ERROR: aswip:           88  isotachs were nonzero.
 ERROR: aswip:           90  isotachs were nonzero.

The following is Keith's solution:

1) Download and install Jaime's adcircpy via pip (pip install adcircpy)
2) Run his command "best_track_file --save-path NWS_BT_SANDY_fort.20 --remove-EX Sandy2012
3) Run aswip ./bin/aswip -n 20 -m 4 -z 2

as Keith mentioned, **thr option of --remove-EX** is in the his forecast_forcing branch https://github.com/krober10nd/adcircpy/blob/feature/forecast_forcing/adcircpy/cmd/best_track_file.py

Don't see the option of --remove-EX in the latest adcircpy main branch.

**I am wondering is there a standard process in the latest adcircpy to deal with the pre-processing for fort.22 file before using awisp?**

If it is only be addressed in Keith's forecast_forcing branch, I will fork this branch and have a try.

Thanks.

**Comment by SorooshMani-NOAA** [comment]
@Jiangchao3 I suggest that you take a look at [`stormevents`](https://github.com/oceanmodeling/StormEvents) package too. You can download any storm track info as a dataframe, manipulate/add/remove its entries and then write it to a `.22` file. Then you can use that file in `adcircpy` to setup the best track forcing.

Currently `adcircpy` doesn't have an active developer and relies mostly on ADCIRC user community for features additions. So if you'd like to add a new feature or bring back a useful feature that never got merged, you can do so and start a pull request. 

@saeed-moghimi-noaa do you have any comments about dev contributions or future of `adcircpy`?

**Comment by Jiangchao3** [comment]
@SorooshMani-NOAA Thanks for the recommendation. I will go to have a look at stormevents.
