### ISSUE TITLE
Extracting Hamtide constituents fails

### ISSUE THREAD

**Issue by SanderHulst** [noaa-ocs-modeling/adcircpy#176]
I must admit that I do not understand why hamtide constituent extraction is all of a sudden failing with the eushelf mesh.

```
Traceback (most recent call last):
  File "/nfs/ecflow/3143/mgforecast/202308310800/mgmodels/adcirc/eushelf_198580e109629n3_onefx/run/202308310800/preprocess/update_control_files.job2", line 112, in <module>
    driver.write('./', overwrite=True, fort22=None)
  File "/nfs/apps/hpc-workflow/app/mgmodels/hydrodynamic/adcirc/preprocess.py", line 79, in write
    f.write(self.fort15('hotstart'))
  File "/opt/apps/python/gcc/3.10.5/lib/python3.10/site-packages/adcircpy/fort15.py", line 301, in fort15
    f.append(self.get_tidal_forcing())
  File "/opt/apps/python/gcc/3.10.5/lib/python3.10/site-packages/adcircpy/fort15.py", line 613, in get_tidal_forcing
    amp, phase = self.mesh.forcings.tides.tidal_dataset(constituent, vertices)
  File "/opt/apps/python/gcc/3.10.5/lib/python3.10/site-packages/adcircpy/forcing/tides/dataset.py", line 26, in __call__
    return self.get_amplitude(constituent, vertices), self.get_phase(constituent, vertices)
  File "/opt/apps/python/gcc/3.10.5/lib/python3.10/site-packages/adcircpy/forcing/tides/hamtide.py", line 50, in get_amplitude
    return self._get_interpolation('elevation', 'AMPL', constituent, vertices) * 0.01
  File "/opt/apps/python/gcc/3.10.5/lib/python3.10/site-packages/adcircpy/forcing/tides/hamtide.py", line 120, in _get_interpolation
    values = griddata(
  File "/opt/apps/python/gcc/3.10.5/lib/python3.10/site-packages/scipy/interpolate/ndgriddata.py", line 260, in griddata
    ip = LinearNDInterpolator(points, values, fill_value=fill_value,
  File "interpnd.pyx", line 277, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "interpnd.pyx", line 78, in scipy.interpolate.interpnd.NDInterpolatorBase.__init__
  File "interpnd.pyx", line 194, in scipy.interpolate.interpnd._check_init_shape
ValueError: invalid shape for input data points

```
What I think that happens is numpy 1.21.0 (🤷‍♂️ ) causes some problems when no Hamtide data is masked and, in the code below, zi.mask is a scalar False.

```
   def _get_interpolation(
        self, variable: str, netcdf_variable: str, constituent: str, vertices: np.ndarray,
    ) -> np.ndarray:
        self._assert_vertices(vertices)

        xq = np.asarray([x + 360.0 if x < 0.0 else x for x in vertices[:, 0]]).flatten()
        yq = vertices[:, 1].flatten()
        dx = (self.x[-1] - self.x[0]) / len(self.x)
        xidx = np.logical_and(self.x >= np.min(xq) - 2.0 * dx, self.x <= np.max(xq) + 2.0 * dx)
        dy = (self.y[-1] - self.y[0]) / len(self.y)
        yidx = np.logical_and(self.y >= np.min(yq) - 2.0 * dy, self.y <= np.max(yq) + 2.0 * dy)
        xi, yi = np.meshgrid(self.x[xidx], self.y[yidx])
        xi = xi.flatten()
        yi = yi.flatten()
        dataset = self._get_dataset(variable, constituent)
        zi = dataset[netcdf_variable][yidx, xidx].flatten()
        values = griddata(
            (xi[~zi.mask].flatten(), yi[~zi.mask].flatten()),
            zi[~zi.mask].flatten(),
            (xq, yq),
            method='linear',
            fill_value=np.nan,
        )
        nan_idxs = np.where(np.isnan(values))
        values[nan_idxs] = griddata(
            (xi[~zi.mask].flatten(), yi[~zi.mask].flatten()),
            zi[~zi.mask].flatten(),
            (xq[nan_idxs], yq[nan_idxs]),
            method='nearest',
        )
        return values

```
I suspect that in that case, xi remains to be a 2d array with a singleton dimension. By adding flatten(), you ensure the 1D that griddata expects.

@SorooshMani-NOAA , @WPringle , do you agree?

**Comment by SorooshMani-NOAA** [comment]
@SanderHulst I remember having some issues with Hamtide unittests with netcdf > 1.6. But then yesterday in order to fix tests for python 3.11, I had to remove limit of netcdf < 1.6 from the dependencies. Since I didn't see any errors in the tests I assumed with the latest netcdf4 available, the hamtide issue was resolved. Maybe what you're seeing is related to this update.

You can try installing netcdf < 1.6 on a python < 3.11 version environment and see if this issue is resolved or not. If it is, then we have to find out why hamtide fails with the latest netcdf version. As a shortterm solution I can add back the limit on netcdf, but also add limit on python version to avoid the issue, knowing that the issue needs to be addressed at some point.

**Comment by SanderHulst** [comment]
The problem occurred with netcdf4==1.5.8 and python3.9 when I call tide_gen on my CentOS9.

On our cluster we have the same netcdf4 package, but python 3.10.5

**Comment by SorooshMani-NOAA** [comment]
That's strange! When did this start happening? After yesterday's changes? Is it a new installation with a new env or is it an old installation just with the updated code?

**Comment by SanderHulst** [comment]
| old installation just with the updated code
This one. I was modifying the eushelf fort.14 file as I figured out to set_open() boundaries intersecting with a polygon. Then the problem started popped up. I went back to my original fort.14 and still encounter the problem.

**Comment by SanderHulst** [comment]
Would there have been a problem caused by geopandas 0.10 vs 0.13?

**Comment by SorooshMani-NOAA** [comment]
> Would there have been a problem caused by geopandas 0.10 vs 0.13?

Not that I know of! So if you go back to old code with original fort.14 does it still happen? I know old code has constituents issues, but just for checking!

**Comment by SanderHulst** [comment]
```
        dataset = self._get_dataset(variable, constituent)
        zi = dataset[netcdf_variable][yidx, xidx].flatten()
        masked_xi = xi[~zi.mask]
        masked_xi_flat = xi[~zi.mask].flatten()
        import pdb;pdb.set_trace()

(Pdb) masked_xi.shape
(1, 399)
(Pdb) masked_xi_flat.shape
(399,)
(Pdb) mask = np.array(xi * False, dtype=bool)
(Pdb) mask.shape
(399,)
(Pdb) xi[~mask].shape
(399,)

```
SH: netcdf > 1.4.1 always return a masked array. The numpy masked array module sets a scalar
mask as an optimization when elements are (un)masked. With a scalar mask, a numpy
array with a singleton dimension is not squeezed to a 1D array, that only happens with
masks the same size as the data.

Hence, the behavior changes depending where your boundary points are.

I'll prepare a PR
