### ISSUE TITLE
Adcircpy Maintainer

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/adcircpy#178]
We've been trying to transfer the maintenance of AdcircPy to the community of users for some time. So far we haven't had any luck! @WPringle @SanderHulst @saeed-moghimi-noaa it would be great if we could discuss and find a solution for this.

If we cannot find any good solutions (or reasons to keep it alive) we might need to deprecate AdcircPy

**Comment by WPringle** [comment]
Hmm I think it is useful, have been using it for current workflow and teaching a predoc how to use. 
And it is also needed for NOAA's EnsemblePerturbation. 
Obviously I see that if SCHISM is being used by NOAA more then adcircpy may be less of a priority.

If it is really to much work to continue have for NOAA (although may consider how to use in STOFS-2D-Global workflow) then could ask to be integrated onto the adcirc GitHub or could be integrated into our OceanMesh Github where we also have a user community.

**Comment by WPringle** [comment]
The other thing is that if we consider the CoastalApp and the idea that things can be modular then need adcircpy to swap out SCHISM and ADCRIC interchangeably. So don't see why whoever is managing CoastalApp could not also occasionally tend to adcircpy when PR comes up, especially if the automatic unit tests can be working

**Comment by SanderHulst** [comment]
I intend adcircpy to be part of my companies workflow. I was afraid that I needed to write the fort.14 and fort.15 stuff all over again, and then I found adcircpy and ocsmesh. You save me a lot of work so I won't mind chipping in.

In the future, I might take a look at SCHISM as well when I (loosely) couple storm surge with our WAVEWATCH model.

**Comment by saeed-moghimi-noaa** [comment]
@SanderHulst 

Hi there,

We are very pleased to know that these tools are useful for you.

Best,
-Saeed

**Comment by SorooshMani-NOAA** [comment]
It's good to know that `adcircpy` is being actively used. As @WPringle pointed out, OCS's own `coupledmodeldriver` and in turn `ensembleperturbation` do use it as well. I'm also very glad that @SanderHulst is willing to help.

My understanding is that on NOAA side no one is actively using `adcircpy` either directly or through any of the downstream packages mentioned above. However as @saeed-moghimi-noaa has previously pointed out, `adcircpy` is a very useful tool for anyone who wants to get started, or even more advanced users.

I, as a developer from NOAA side, can continue responding to pull requests, but I'm not an ADCIRC user, there used to be a couple of others on our side who would also use `adcircpy`, and not just maintain it. That's why I wanted to check if you think it'd be better to move it to a more open organization (like [oceanmodeling](https://github.com/oceanmodeling)) so that others (i.e. non-NOAA active ADCIRC users) could be the main maintainers of the repo as well.

@WPringle if we move it to one of these open organizations, maybe still it makes sense to keep it separate from the mesh modification tools. Personally I believe, if you're really thinking about doing that, it actually makes sense to port the *setup* portions of python OceanMesh package to `adcircpy` and maintain them separately or something like that.

Of course if we want to transfer the repo from `ocs-modeling` @saeed-moghimi-noaa should make the final decision.

**Comment by SorooshMani-NOAA** [comment]
After further discussion, the transfer of ownership to OceanModeling seems like a good choice. We'll follow up with required permissions for the transfer.

**Comment by saeed-moghimi-noaa** [comment]
Done!
